# Generated by chatGPT

import os
import shutil
import sys
import xml.etree.ElementTree as ET


def extract_text(element):
    """Helper function to extract text from XML nodes."""
    return ''.join(element.itertext()).strip() if element is not None else ""

def clean_arg_string(arg_string):
    end_idx = arg_string.find(')')
    if end_idx != -1:
        return arg_string[:end_idx + 1]

    return arg_string


def parse_function(member):
    """Parses a single function from the XML."""
    type = extract_text(member.find("type"))
    name = extract_text(member.find("name"))
    argsstring = clean_arg_string(extract_text(member.find("argsstring")))
    brief = extract_text(member.find("briefdescription/para"))
    detailed = extract_text(member.find("detaileddescription/para"))
    params_desc = member.findall("detaileddescription/para/parameterlist/parameteritem")
    params = member.findall("param")
    return_type = extract_text(member.find("type"))
    return_desc = extract_text(member.find("detaileddescription/para/simplesect[@kind='return']/para"))

    # Markdown formatting
    md = f"### `{type} {name}{argsstring}`\n\n"
    if brief or detailed:
        md += f"**Description**:<br>*{brief if brief else detailed}*\n\n"

    if return_type != "void" and return_type != "":
        md += f"*Returns: `{return_type}`*<br>"
        md += f"*&nbsp;&nbsp;&nbsp;&nbsp;{return_desc}*\n\n"

    # Parse parameters
    parameters = []
    for param in params:
        param_type = extract_text(param.find("type"))
        param_name = extract_text(param.find("declname"))
        parameters.append((param_type, param_name))

    for param_desc in params_desc:
        param_name = extract_text(param_desc.find("parameternamelist/parametername"))
        param_description = extract_text(param_desc.find("parameterdescription/para"))

        param_type = ""
        for param in parameters:
            if param[1] == param_name:
                param_type = param[0]

        if param_type == "":
            continue

        md += f"*`{param_type} {param_name}`*<br>&nbsp;&nbsp;&nbsp;&nbsp;*{param_description if param_description else 'No description'}* \n\n"

    md += "\n"
    return md

def parse_fields(member):
    """Parses a single field from the XML."""
    type = extract_text(member.find("type"))
    name = extract_text(member.find("name"))
    brief = extract_text(member.find("briefdescription/para"))
    detailed = extract_text(member.find("detaileddescription/para"))
    initializer = extract_text(member.find("initializer"))

    md = f"`{type} {name} {initializer}`<br>"
    md += f"&nbsp;&nbsp;**Description:** {brief if brief else detailed} \n\n"
    return md

def parse_class(xml_file, compound_kind):
    """Parses the class from the XML file and generates Markdown."""
    tree = ET.parse(xml_file)
    root = tree.getroot()

    # Locate the class definition
    class_def = root.find(".//compounddef")
    class_name = extract_text(class_def.find("compoundname"))
    brief = extract_text(class_def.find("briefdescription/para"))
    detailed = extract_text(class_def.find("detaileddescription/para"))

    # Markdown for class
    md = f"---\n"
    md += f"## {compound_kind} {class_name}\n\n"
    if detailed:
        desc_text = f"{detailed}"
    else:
        desc_text = f"{brief}"

    md += f"**Description**:<br>"
    md += f"{desc_text}\n\n"

    md += f"---\n\n"

    # Parse functions
    section_functions = class_def.find("sectiondef[@kind='public-func']")
    if section_functions is not None:
        md += "### Public Functions\n\n"
        for member in section_functions.findall("memberdef[@kind='function']"):
            md += parse_function(member)

    section_fields = class_def.find("sectiondef[@kind='public-attrib']")
    if section_fields is not None:
        md += "### Public Fields\n\n"
        variable_members = section_fields.findall("memberdef[@kind='variable']")
        for member in variable_members:
            md += parse_fields(member)

    md += f"---\n\n"

    return md


def generate_markdown(xml_dir, output_file):
    if not os.path.exists(xml_dir):
        print(f"Error: XML directory {xml_dir} does not exist")
        sys.exit(1)

    index_path = os.path.join(xml_dir, "index.xml")
    if not os.path.exists(index_path):
        print(f"Error: Index.xml not found at {index_path}")
        sys.exit(1)

    tree = ET.parse(index_path)
    root = tree.getroot()

    with open(output_file, "w", encoding="utf-8") as md:
        md.write(f"# API Documentation\n\n")

        for compound in root.findall(".//compound"):
            compound_name = compound.get("refid")
            compound_kind = compound.get("kind")

            if compound_kind not in ["class", "struct", "enum"]:
                continue

            detail_path = os.path.join(xml_dir, f"{compound_name}.xml")
            if os.path.exists(detail_path):
                parsed = parse_class(detail_path, compound_kind)
                md.write(parsed)


def cleanup_directory(directory):
    """Deletes the specified directory and all its contents."""
    if os.path.exists(directory):
        shutil.rmtree(directory)
        print(f"Deleted directory: {directory}")
    else:
        print(f"Directory {directory} does not exist.")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python markdown_docu_builder.py <xml-dir> <output-file>")
        sys.exit(1)
    xml_directory = sys.argv[1]
    output_file = sys.argv[2]
    generate_markdown(xml_directory, output_file)
    cleanup_directory(xml_directory)
