# Generated by chatGPT

import os
import shutil
import sys
import xml.etree.ElementTree as ET


def extract_text(element):
    """Helper function to extract text from XML nodes."""
    return ''.join(element.itertext()).strip() if element is not None else ""


def parse_function(member):
    """Parses a single function from the XML."""
    name = extract_text(member.find("name"))
    definition = extract_text(member.find("definition"))
    argsstring = extract_text(member.find("argsstring"))
    brief = extract_text(member.find("briefdescription/para"))
    params_desc = member.findall("detaileddescription/para/parameterlist/parameteritem")
    params = member.findall("param")
    return_type = extract_text(member.find("type"))
    return_desc = extract_text(member.find("detaileddescription/para/simplesect[@kind='return']/para"))

    # Markdown formatting
    md = f"### `{definition}{argsstring}`\n\n"
    if brief:
        md += f"**Description**:<br>*{brief}*\n"

    if return_type == "":
        return_type = "void"

    md += "\n| **Type** | **Name** | **Description** |\n"
    md += "| --- | --- | --- |\n"
    md += f"| {return_type} | *Return* | {return_desc} |\n"

    # Parse parameters
    parameters = []
    for param in params:
        param_type = extract_text(param.find("type"))
        param_name = extract_text(param.find("declname"))
        parameters.append((param_type, param_name))

    for param_desc in params_desc:
        param_name = extract_text(param_desc.find("parameternamelist/parametername"))
        param_description = extract_text(param_desc.find("parameterdescription/para"))

        param_type = ""
        for param in parameters:
            if param[1] == param_name:
                param_type = param[0]

        md += f"| {param_type} | {param_name} | {param_description if param_description else 'No description'} |\n"

    md += "\n"
    return md


def parse_class(xml_file):
    """Parses the class from the XML file and generates Markdown."""
    tree = ET.parse(xml_file)
    root = tree.getroot()

    # Locate the class definition
    class_def = root.find(".//compounddef")
    class_name = extract_text(class_def.find("compoundname"))
    brief = extract_text(class_def.find("briefdescription/para"))
    detailed = extract_text(class_def.find("detaileddescription/para"))

    # Markdown for class
    md = f"---\n"
    md += f"## Class {class_name}\n\n"
    if detailed:
        desc_text = f"{detailed}"
    else:
        desc_text = f"{brief}"

    md += f"**Description**:<br>"
    md += f"{desc_text}\n\n"

    md += f"---\n"

    # Parse functions
    section = class_def.find("sectiondef[@kind='public-func']")
    if section is not None:
        md += "### Public Functions\n\n"
        for member in section.findall("memberdef[@kind='function']"):
            md += parse_function(member)

        md += "---\n"

    return md


def generate_markdown(xml_dir, output_file):
    if not os.path.exists(xml_dir):
        print(f"Error: XML directory {xml_dir} does not exist")
        sys.exit(1)

    index_path = os.path.join(xml_dir, "index.xml")
    if not os.path.exists(index_path):
        print(f"Error: Index.xml not found at {index_path}")
        sys.exit(1)

    tree = ET.parse(index_path)
    root = tree.getroot()

    with open(output_file, "w", encoding="utf-8") as md:
        md.write(f"# API Documentation\n\n")

        for compound in root.findall(".//compound"):
            compound_name = compound.get("refid")
            compound_kind = compound.get("kind")

            if compound_kind not in ["class", "namespace"]:
                continue

            detail_path = os.path.join(xml_dir, f"{compound_name}.xml")
            if os.path.exists(detail_path):
                parsed = parse_class(detail_path)
                md.write(parsed)


def cleanup_directory(directory):
    """Deletes the specified directory and all its contents."""
    if os.path.exists(directory):
        shutil.rmtree(directory)
        print(f"Deleted directory: {directory}")
    else:
        print(f"Directory {directory} does not exist.")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python markdown_docu_builder.py <xml-dir> <output-file>")
        sys.exit(1)
    xml_directory = sys.argv[1]
    output_file = sys.argv[2]
    generate_markdown(xml_directory, output_file)
    cleanup_directory(xml_directory)
